FROM node:8-alpine

ARG FILE=customerService.js
ENV NODE_ENV production

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY package.json package-lock.json /usr/src/
COPY $FILE /usr/src/index.js

RUN npm install

EXPOSE 3000

CMD npm start
