version: '3'
services:

  customers:
    build: .
    command: npm start
    volumes:
      - ./customerService.js:/usr/src/index.js
      - /usr/src/node_modules

  invoices:
    build: .
    command: npm start
    volumes:
      - ./invoiceService.js:/usr/src/index.js
      - /usr/src/node_modules

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kong:
    build: ./kong/
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CUSTOM_PLUGINS=external-oauth

  konga:
    image: pgbi/kong-dashboard:v2
    ports:
      - 8080:8080

volumes:
  mongo-data:
  postgres-data:
