version: '3'
services:
  customers:
    container_name: customers
    image: xvincentx/apigatewayplayground_customers
    command: ./node_modules/.bin/nodemon -- --inspect=0.0.0.0 customerService.js
    ports:
      - 9229:9229

  invoices:
    container_name: invoices
    image: xvincentx/apigatewayplayground_invoices
    command: ./node_modules/.bin/nodemon -- --inspect=0.0.0.0 invoiceService.js
    ports:
      - 9228:9229

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db

  gateway:
    container_name: gateway
    image: xvincentx/apigatewayplayground_gateway
    ports:
      - 81:80
      - 9876:9876
    environment:
      - LOG_LEVEL=debug
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
