version: '3'
services:

  customers:
    container_name: customers
    build: .
    command: npm start
    volumes:
      - ./customerService.js:/usr/src/index.js
      - /usr/src/node_modules

  invoices:
    container_name: invoices
    build: .
    command: npm start
    volumes:
      - ./invoiceService.js:/usr/src/index.js
      - /usr/src/node_modules

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db

  kong-database:
    container_name: postgres
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kong:
    container_name: kong
    build: ./kong/
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database

  konga:
    container_name: konga
    image: pgbi/kong-dashboard:v2
    ports:
      - 8080:8080

volumes:
  mongo-data:
  postgres-data:
