version: '3'
services:

  customers:
    build: .
    command: node ./customerService.js
    entrypoint: node ./customerService.js
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules

  invoices:
    build: .
    command: node ./invoiceService.js
    entrypoint: node ./invoiceService.js
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - postgres-data:/var/lib/postgresql/data


  data:
    image: tianon/true
    volumes:
      - mongo-data:/data/db
      - postgres-data:/var/lib/postgresql/data

  kong:
    image: kong:latest
    restart: always
    expose:
      - 8000
      - 8443
      - 8001
      - 7946
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database

volumes:
  mongo-data:
  postgres-data:
