version: 2
jobs:
  build:
    docker:
      - image: moregreenhouse/tm-base
    working_directory: ~/apigatewayplayground
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - run: docker-compose push
      - run: "docker tag apigatewayplayground_customers $DOCKER_USER/apigatewayplayground_customers:$CIRCLE_BRANCH"
      - run: "docker tag apigatewayplayground_invoices $DOCKER_USER/apigatewayplayground_invoices:$CIRCLE_BRANCH"
      - run: "docker push $DOCKER_USER/apigatewayplayground_customers:$CIRCLE_BRANCH"
      - run: "docker push $DOCKER_USER/apigatewayplayground_invoices:$CIRCLE_BRANCH"

